version: "3.1"

networks:
  gitea:
    external: false


services:
  server:
    image: gitea/gitea:{$VERSION}
    container_name: gitea
    environment:
      - USER_UID=${PUID}
      - USER_GID={$GUID}
    restart: always
    networks:
      - gitea
    volumes:
      - ${CONFIG}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{$PORT}:3000"
      - "{$SSH}:22"
