---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:${VERSION}
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}:/config
    ports:
      - ${HTTPPORT}:80
      - ${HTTPSPORT}:443
    restart: unless-stopped
