---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:${VERSION}
    container_name: jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
      - RUN_OPTS= ${RUNOPTS}
    volumes:
      - ${CONFIG}:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - ${PORT}:9117
    restart: unless-stopped
