version: "3.2"
services:
  overseerr:
    image: sctx/overseerr:${VERSION}
    container_name: overseerr
    environment:
      - LOG_LEVEL=${LOGLEVEL}
      - TZ=${TZ}
      - PORT=${PORT}
    ports:
      - ${PORT}:5055
    volumes:
      - ${CONFIG}:/app/config
      - ${LOGO}:/app/public/logo_full.svg
    restart: unless-stopped
