version: "3.2"
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:${VERSION}
    restart: unless-stopped
    ports:
      - ${PORT}:7878
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}:/config
      - ${MEDIA}:${MEDIA}:rw
      - ${DOWNLOAD}:${DOWNLOAD}:rw
    healthcheck:
      test: curl --fail http://localhost:${PORT}/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    
