---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}:/config
      - ${BOOKS}:${BOOKS}:rw
      - ${DOWNLOAD}:${DOWNLOAD}:rw
    ports:
      - 8787:8787
    restart: unless-stopped


