version: "3.2"
services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:${VERSION}
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - ${PORT}:8080
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}:/config
      - ${DOWNLOAD}:${DOWNLOAD}:rw
