services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION}
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - ${CONFIG}:/app/data
    ports:
      - ${PORT}:3001
    restart: unless-stopped
